#!/bin/bash
# script to setup newrea.out cht mesh generation case from a gmsh .geo files
# arg 1 = working directory
# arg 2 = name of geo file (exclude .geo)
# arg 3 = name of .msh output file (exclude.msh)
src=$PWD
# echo "$src"
# exit 1
cd $1
gmsh $2".geo" -3 -order 2 -o $3".msh" -format msh22
gmsh2nek << EOF
3
$3
0
EOF
head -c20 *re2

cd $src/chtsetup-files || { echo 'file template dir does not exist, check script' ; exit 1; }
cp SIZE *usr *.rea $1/.
cd $1
mv *usr $3".usr"
mv *.rea $3".rea"
head -c20 *re2
echo $'\nSetup sidesets in usr file from .geo file now.'
key='a'
while [ "$key" != '' ]; do
    read -n1 -r -p "Press space to continue..." key
done
ls

genmap << EOF
$3
0.1
EOF
makenek $3
nekmpi $3 4
touch $3"-prenek.rea"
cd $src/chtsetup-files
cat toprea >> $1/$3"-prenek.rea"
cat $1/newrea.out >>  $1/$3"-prenek.rea"
cat botrea >>  $1/$3"-prenek.rea"
cd $1
mkdir genfiles
op=$3-"prenek.rea"
shopt -s extglob
mv !($op|*.geo|genfiles) genfiles/.
echo "run prenek script to merge solid and fluid"
