#!/bin/bash
# script to setup newrea.out cht mesh generation case from gmsh .geo files
# add SIZE, usr, rea, par template files in script directory in folder "chtsetup-files"
# arg 1 = working directory - must contain a fluid and a solid folder
# arg  = name of geo file (exclude .geo) ---> REMOVED - make fluid/solid
# name of .msh output file (exclude.msh) = solid or fluid
# arg 2 = no. of processors for nekmpi run
src=$PWD
cd $1
solid=$1"/solid"
fluid=$1"/fluid"
# echo "$src"
# exit 1
for folder in $solid $fluid
do
    cd $folder
    opname=$(basename "${folder}")
    gmsh $opname".geo" -3 -order 2 -o $opname".msh" -format msh22
    echo "$opname"
    gmsh2nek << EOF
3
$opname
0 
EOF
    head -c20 *re2

    if [ -e SIZE ] && [ -e $opname.usr ] && [ -e $opname.rea ]
    then
        echo $'\nNek case files detected.Proceeding to nek operations.\n'
        key='a'
        while [ "$key" != '' ]; do
        read -n1 -r -p "Press space to continue..." key
    done
    else
        echo $'\nNek case files not detected. Copying templates...\n'
        cd $src/chtsetup-files || \
         { echo 'file template dir does not exist, check script' ; exit 1; }
        cp SIZE *usr *.rea $folder
        cd $folder
        mv *usr $opname".usr"
        mv *.rea $opname".rea"
        head -c20 *re2
        echo $'\nSetup sidesets in usr file from .geo file now.'
        key='a'
        while [ "$key" != '' ]; do
        read -n1 -r -p "Press space to continue..." key
    done
    fi

    genmap << EOF
$opname
0.1
EOF
    makenek $opname
    nekmpi $opname $2
    touch "new"$opname".rea"
    cd $src/chtsetup-files
    cat toprea >> $folder/"new"$opname".rea"
    cat $folder/newrea.out >>  $folder/"new"$opname".rea"
    cat botrea >>  $folder/"new"$opname".rea"
    cd $folder
    mkdir genfiles
    op="new"$opname".rea"
    shopt -s extglob
    mv !($op|*.geo|*.usr|SIZE|$opname.re*|genfiles) genfiles/.
    echo "run prenek script to merge solid and fluid"
