#!/bin/bash
#shopt -s extglob
# script to setup newrea.out cht mesh generation case from gmsh .geo files
# add SIZE, usr, rea, par template files in script directory in folder "chtsetup-files"
# arg 1 = working directory - must contain a fluid and a solid folder
# arg  = name of geo file (exclude .geo) ---> REMOVED - make fluid/solid
# name of .msh output file (exclude.msh) = solid or fluid
# arg 2 = no. of processors for nekmpi run
src=$PWD
cd $1
solid=$1"/solid"
fluid=$1"/fluid"
# echo "$src"
# exit 1
for folder in $solid $fluid
do
    cd $folder
    echo "$folder"
    opname=$(basename "${folder}")
    gmsh $opname".geo" -3 -order 2 -o $opname".msh" -format msh22
    echo "$opname"
    gmsh2nek << EOF
3
$opname
0 
EOF
    head -c20 *re2

    if [ -e SIZE ] && [ -e $opname.usr ] && [ -e $opname.rea ]
    then
        echo $'\nNek case files detected.Proceeding to nek operations.\n'
        key='a'
        while [ "$key" != '' ]; do
	    echo "Press space to continue..." 
#            read key
            read -n1 key </dev/tty
        done
    else
        echo $'\nNek case files not detected. Copying templates...\n'
        cd $src/chtsetup-files || \
         { echo 'file template dir does not exist, check script' ; exit 1; }
        cp SIZE *usr *.rea $folder
        cd $folder
        mv *usr $opname".usr"
        mv *.rea $opname".rea"
        head -c20 *re2
        echo $'\nSetup sidesets in usr file from .geo file, and SIZE file.'
        key='a'
        while [ "$key" != '' ]; do
	    echo "Press space to continue..." 
#            read key
	    read -n1 key </dev/tty

        done
    fi

    genmap << EOF
$opname
0.1
EOF
    makenek $opname || exit 1
    echo "$opname"
    nekmpi $opname $2 || exit 1
    op="new"$opname".rea"
    touch $op
    cd $src/chtsetup-files
    cat toprea >> $folder/$op
    cat $folder/newrea.out >>  $folder/$op
    cat botrea >>  $folder/$op
    cd $folder
#    mkdir genfiles
#    mv !'(*.geo|*.usr|SIZE|*.re*|genfiles)' genfiles/.
    echo "run prenek script to merge solid and fluid"
    [ ! -d "../prenek" ] && mkdir ../prenek
    cp $op ../prenek/  
done
cd ../prenek
prex << EOF
chtrea
3
fluid
solid
EOF
reatore2 << EOF
chtrea
cht
EOF
cp cht.re2 ../.
echo "re2 generated in working directory."
