#!/bin/bash
#shopt -s extglob
# arg 1 - working dir where newrea.out lives
# arg 2 - output rea name
# script needs toprea and botrea files in folder "chtsetup-files" - basically 
# top and bottom of any 3D rea file from examples
src=$PWD
cd $1

lineno=0
bcstr="BOUNDARY CONDITIONS"
while IFS= read -r line; do
    lineno=lineno+1
    if [[ "$line" == *"$bcstr"* ]]
	    sed -i "$lineno,/end/s/P/ " newrea.out
	    break
    fi
done < newrea.out

op=$2".rea"
rm $op
touch $op
cd $src/chtsetup-files
cat toprea >> $1/$op
cat $1/newrea.out >>  $1/$op
cat botrea >>  $1/$op
