#!/bin/bash
# script to rename nek output files from a restarted run
# place script where casefiles <casename>.f12345 are
# run ./rename <arg>, where <arg> is the increment in the
# file numbers to make file numbers consistent chronologically

for i in *.f*; 
do
  fullname=$(basename "$i")
  fname="${fullname%.*}" # extract case name
  inc=$1
  NUM="${fullname##*.}" # extract extension
  NUM=${NUM:1:5}  # drop the f in f12345
  NUM=$(echo "$NUM+$inc" | bc) # add increment
  str="$NUM"
  while [ ${#str} -lt 5 ]; do # pad with zeros
      str="0"$str
  done
  new="${fname}.f${str}"
  mv $i $new
done
