#!/bin/bash
# script to rename nek output files
# run ./rename <arg>, where <arg> is the increment in the
# file numbers
files=$PWD/*.f*

for i in *.f*; 
do
  fullname=$(basename "$i")
  fname="${fullname%.*}" # extract case name
  inc=$1
  NUM="${fullname##*.}" # extract extension
  NUM=${NUM:1:5}  # drop the f in f12345
  NUM=$(echo "$NUM+$inc" | bc) # add increment
  str="$NUM"
  while [ ${#str} -lt 5 ]; do # pad with zeros
      str="0"$str
  done
  new="${fname}.f${str}"
  mv $i $new
done

# for i in *.f* ; do
#  NUM=$(echo "$i" | tr -dc '0-9')
#  NUM=$(echo "$NUM+0" | bc)
#  str="$NUM"
  # echo "STR:$str"
#  old="${fname}.f${str}"
  # echo "NEWSTR:$str"
  new2="${fname}.f${str}"
  # echo "OLD:$old"
  # echo "NEW:$new2"
#  echo "$new2"
#  mv $old $new2
#done
