#!/bin/bash
# ##################################################
# transfer directory - not recommended by BW
# ##################################################
# echo "Enter destination GO [ end#point:/path ] "
# read DEST
# DEST="$DEST/"
# echo "Enter source GO [ end#point:/path ]"
# read SRC
# SRC="$SRC/"
# echo "Enter file pattern to transfer from source directory [Ex:  \*.dat ]:"
# read PATTERN
# PATTERN="\*.tar"
# echo "checking source and file pattern...last 3 entries..."
# bwpy-environ globus ls --filter "~$PATTERN" $SRC | tail -3
# echo "checking destination directory existence ... first 3 entries"
# bwpy-environ globus ls $DEST | head -3
# echo "ctrl-c to quit, or press return to initiate transfer"
# read RESPONSE
# set -x
# for filename in `bwpy-environ globus ls --filter "~$PATTERN" $SRC`
# do
#   bwpy-environ globus transfer -- $SRC$filename $DEST$filename
# done

# ##################################################
# transfer individual files - BW recommends archives
# ##################################################
DEST="2341a858-96cd-11e9-bf5c-0e4a062367b8:/home/achaube/bwop/bw-qchannel.tar"
SRC="d59900ef-6d04-11e5-ba46-22000b92c6ec:/projects/sciteam/bahg/Nek5000/run/bw-qchannel.tar"
echo "checking destination directory existence ... first 3 entries"
bwpy-environ globus ls $DEST | head -3
echo "ctrl-c to quit, or press return to initiate transfer"
read RESPONSE
bwpy-environ globus transfer $SRC $DEST
